#! /bin/sh

# SXKD
sxhkd &

# Desktops
bspc monitor -d 1 2 3 4 5 6 7 8

# Borders
bspc config border_width            2

# Separation between windows
bspc config window_gap              10

# Paddings
#bspc config top_padding             10
#bspc config bottom_padding          10
#bspc config left_padding            2
#bspc config right_padding           2

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
xsetroot -cursor_name left_ptr &

# Wallpaper
feh --bg-fill ~/dotfiles/kali-wallpapers/kali-neon-16x9.png

# Polybar
~/.config/polybar/./launch.sh &

# Picom
picom &

# Rules
# bspc rule -a firefox desktop='^8' state=floating follow=on
