#! /bin/sh

# SXKD
sxhkd &

# Unique Monitor
bspc monitor -d 1 2 3 4 5 6 7 8

# Multiple Monitors
# bspc monitor HDMI-A-0 -d 2 3 4 5
# bspc monitor DVI-D-0 -d 1
# xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rotate normal --output DisplayPort-0 --mode 1440x900 --left-of HDMI-A-0

# Borders
bspc config border_width            0

# Separation between windows
bspc config window_gap              10

# Borders
bspc config border_width            1

# Paddings
#bspc config top_padding             10
#bspc config bottom_padding          10
#bspc config left_padding            2
#bspc config right_padding           2

# Configs
bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

# Rules
# Use xprop | grep CLASS to obtain the name of the app

# Web Proxy: BurpSuite
bspc rule -a burp-StartBurp desktop='^1' follow=on focus=on
# Terminal: Kitty
bspc rule -a kitty desktop='^2' follow=on focus=on
# Web Browser: Firefox
bspc rule -a Firefox-esr desktop='^3' follow=on focus=on
# File Explorer: Thunar
bspc rule -a Thunar desktop='^4' follow=on focus=on
# IDE: Visual Studio Code
bspc rule -a Code desktop='^5' follow=on focus=on
# Markdown Editor: Obsidian
bspc rule -a obsidian desktop='^5' follow=on focus=on

# Set cursor name
xsetroot -cursor_name left_ptr &

# Wallpaper
feh --bg-fill /home/$USER/Pictures/current-wallpaper.jpg

# Polybar
~/.config/polybar/./launch.sh &

# Picom
picom &

# Set the window manager name to fix problems with JDK versions and other broken programs assuming a reparenting window manager for instance.
wmname LG3D &

# Dropbox
dropbox start &
