#! /bin/sh

# SXKD
sxhkd &

# Desktops
bspc monitor HDMI-A-0 -d 2 3 4 5
bspc monitor DVI-D-0 -d 1

# Multiple Monitors Config
xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rotate normal --output DisplayPort-0 --mode 1440x900 --left-of HDMI-A-0
# Borders
bspc config border_width            0

# Separation between windows
bspc config window_gap              10

# Paddings
#bspc config top_padding             10
#bspc config bottom_padding          10
#bspc config left_padding            2
#bspc config right_padding           2

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
xsetroot -cursor_name left_ptr &

# Wallpaper
feh --bg-fill ~/dotfiles/kali-wallpapers/kali-neon-16x9.png

# Polybar
~/.config/polybar/./launch.sh &

# Picom
picom &
